chart-dirs:
  - charts
chart-repos:
  - ankh=https://ankh-is.github.io/charts/
check-version-increment: true
debug: true
remote: origin
validate-chart-schema: true
validate-maintainers: true
validate-yaml: true
